version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/lib/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Go: "
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Tool: "
  - package-ecosystem: "maven"
    directory: "/lib/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Java: "
  - package-ecosystem: "maven"
    directory: "/examples/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Examples(java): "
  - package-ecosystem: "gomod"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Examples(go): "
  - package-ecosystem: "maven"
    directory: "/test/integration/java/frugal-integration-test"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Tests(java): "
  - package-ecosystem: "gomod"
    directory: "/test/integration"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Tests(go): "
  - package-ecosystem: "pip"
    directory: "/lib/python"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "charliekump-wf"
      - "natewoods-wf"
    commit-message:
      prefix: "Python: "
