name: frugal
version: 0.0.1

environment:
  sdk: ^1.13.0

dependencies:
  logging: ^0.11.2
  thrift:
    git:
      url: git@github.com:Workiva/thrift-dart.git
      ref: 0.0.1
  uuid: any

dev_dependencies:
  test: ^0.12.6
