name: frugal
version: 1.0.8

environment:
  sdk: ^1.13.0

dependencies:
  logging: ^0.11.2
  thrift:
    git:
      url: git@github.com:Workiva/thrift-dart.git
      ref: 0.0.4
  uuid: any

dev_dependencies:
  coverage: ^0.7.2
  dart_dev: ^1.0.6
  dart_style: ^0.2.0
  dartdoc: ^0.4.0
  mockito: ^0.11.0
  test: ^0.12.6
