version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/lib/go"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers: 
      - "Workiva/product2"
    commit_message:
      prefix: "Go: "
  - package_manager: "java:maven"
    directory: "/lib/java"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers: 
      - "Workiva/product2"
    commit_message:
      prefix: "Java: "
  - package_manager: "java:maven"
    directory: "/examples/java"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers: 
      - "Workiva/product2"
    commit_message:
      prefix: "Examples: "
  - package_manager: "java:maven"
    directory: "/test/integration/java/frugal-integration-test"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers: 
      - "Workiva/product2"
    commit_message:
      prefix: "Integration Tests: "
  - package_manager: "python"
    directory: "/lib/python"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers: 
      - "Workiva/product2"
    commit_message:
      prefix: "Python: "
